### ISSUE TITLE
Faultfinding USB comms query

### ISSUE THREAD

**Issue by trobbinsfromoz** [LM13700/TF2000-remote-tools#1]
I have Python 3.13 set up on a laptop with Win10 and modified the port to the assigned COM#, and 1200, 8b, no parity, stop bits 2, and used the 'Hardware' flow control setting, and have set up a CH340 USB interface with required wiring.  I run the example.py script (with edited Com#) in Win PowerShell (after changing to my TF2000 folder and activating venv).  When I run a simple sweep, the TF2000 screen then halts with "PRINTER HOLD    RUNNING" and the GEN indicator still on.  There is no csv generated in the output folder.  I repeated with the USB interface port setting flow control changed to Xon/Xoff, but no change to result.  Any thoughts on how to progress ?  Ciao, Tim

**Comment by LM13700** [comment]
Hello Tim,

If only the wiring is correct, the next thing that comes to my mind is the TF2000s serial port configuration, as described in [2. RS232 Communication](https://github.com/LM13700/TF2000-remote-tools#2-rs232-communication). When new data is received it will be immediately printed on the serial output of the python script.

If you have any more questions feel free to ask.

Regards,
Mateusz

**Comment by trobbinsfromoz** [comment]
Hi Mateusz.  I checked the USB interface to RS232 wiring.  Both RTS and CTS lines go high when the USB is inserted to laptop.  RTS then goes low when example.py is run (just probing RS232 lines with no connection to TF2000).  

I then probed when RS232 was connected to TF2000.  CTS line is pulled to ground with TF2000 off, and stays low when TF2000 is on, and through to Printer Hold status.  RTS is pulled just below gnd when RS232 connected to TF2000.  RTS then just goes above gnd after RUN is pressed and through to when Printer Hold status is on.  RTS is pulled just below gnd when STOP is pressed on TF2000.

Does that sound consistent with expected RTS and CTS lines?

**Comment by LM13700** [comment]
Hi Tim.

I have no experience in low-level RS232 debugging, but after a quick search, it appears that the transmitting device should assert RTS when it is ready to send, and the receiving device should assert CTS when it is able to receive. So behavior without TF2000 seems correct. I'm sorry but I'm not sure if I understand correctly state of those pins during TF2000 transmission, CTS line is low all the time even during Printer Hold status? RTS line is high when the TF2000 performs measurement and is still high during Printer Hold status but goes down when STOP is pressed?
I just updated the readme file with a rough RS-232 cable schematic, please read through it and make sure the cable is prepared correctly, as it is not a common crosslinked cable. I would guess that is the problem. Are you also sure that TF2000s serial port configuration is correct?

**Comment by trobbinsfromoz** [comment]
Hi Mateusz, thanks for recent upload of the RS232 wiring diagram.  I had misinterpreted the original cable interface description, and had RX/TX, and RTS/CTS inverted, so have modified that now.  Yes I have the TF2000 print options correct.  However I am still not getting a data file transmitted.

If I have the USB interface connected and example.py running, then the TF2000 starts a sweep but quickly displays Printer Hold.  
If I have the USB interface connected but haven't yet run example.py, then the TF2000 starts and completes the sweep.  But if I then run example.py, there is no response, and no data file generated in the output folder.
If I don't have the USB interface connected, then the TF2000 won't start a sweep and displays Printer Hold.  If I then insert the USB plug, the sweep starts and runs to completion. But when I then run example.py there is no data transfer.

I tried changing the sweep steps to 15, and also the example.py configuration to 15 steps, but no change in outcome.  I tried the Windows Com port settings with Flow Control set to Hardware, or Xon/Xoff, but no change to outcome.

I will try using a non-Windows OS laptop, just in case there is some issue with my Win10 comms or Python config.  Do the USB connected/disconnected actions above occur for your setup?

**Comment by LM13700** [comment]
Hi Tim,
I will be able to test this on my setup in the following week.

**Comment by LM13700** [comment]
Hi Tim.

I have just tested my setup. When no PC is connected to the TF2000 after the first measurement of the sweep the display shows PRINTER HOLD RUNNING and freezes. When the PC is connected via the RS232-USB converter, even without python script running, the entire sweep is performed and the measurement printing is fast enough that the display does not show PRINTER HOLD.  While the python script is running it should print every measurement it receives on the console (see attached image).
![image](https://github.com/user-attachments/assets/48b7c376-772b-4cdb-a77c-8a58bb76fedd)

This suggests that your cable and RS232 - USB configuration are probably correct and the error is on the software side. Can you try running the script on the other computer? Maybe some firewall is blocking COM access to the script? Another thing to try is to use a terminal such as PuTTY to open a COM port using the described configuration and see if any data is displayed.

I hope this helps to find the problem.

**Comment by trobbinsfromoz** [comment]
Ta, thanks for that assistance - much appreciated.  It may be a few days before I can get to the other laptop. Will keep trying :-)
